version: "3.7"
services:
  challenge:
    build: challenge
    ports:
      - 8000:80
    environment:
      - TOKEN_SECRET=382u0hr08hfb
    links:
      - administrator:administrator

  administrator:
    build: administrator
    ports:
      - 8001:80