version: "3.7"
services:
  challenge:
    build: challenge
    ports:
      - 8002:80
    links:
      - administrator:administrator

  administrator:
    build: administrator
    ports: 
      - 8001:80