version: "3.7"
services:
  challenge:
    build: challenge
    ports:
      - 8000:80
    environment:
      - TOKEN_SECRET=382u0hr08hfb
    links:
      - selenium:selenium

  selenium:
    image: selenium/standalone-chrome:85.0
    environment:
      - JAVA_OPTS=-Dwebdriver.chrome.whitelistedIps=